spring:
  application:
    name: stock
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stock_example
    username: root
    password: 1234

